import type { Card } from './decks';

const VERBS: Array<[string, string]> = [
  ['be', 'bo‘lmoq'],
  ['have', 'ega bo‘lmoq'],
  ['do', 'qilmoq'],
  ['say', 'aytmoq'],
  ['go', 'bormoq'],
  ['can', 'qila olmoq'],
  ['get', 'olmoq'],
  ['would', 'qilar edi'],
  ['make', 'yasamoq'],
  ['know', 'bilmoq'],
  ['will', 'qilmoqchi bo‘lmoq'],
  ['think', 'o‘ylamoq'],
  ['take', 'olmoq'],
  ['see', 'ko‘rmoq'],
  ['come', 'kelmoq'],
  ['could', 'qila olar edi'],
  ['want', 'xohlamoq'],
  ['look', 'qaramoq'],
  ['use', 'foydalanmoq'],
  ['find', 'topmoq'],
  ['give', 'bermoq'],
  ['tell', 'aytib bermoq'],
  ['work', 'ishlamoq'],
  ['may', 'mumkin bo‘lmoq'],
  ['should', 'kerak bo‘lmoq'],
  ['call', 'qo‘ng‘iroq qilmoq'],
  ['try', 'urinmoq'],
  ['ask', 'so‘ramoq'],
  ['need', 'kerak bo‘lmoq'],
  ['feel', 'his qilmoq'],
  ['become', 'aylanmoq'],
  ['leave', 'ketmoq'],
  ['put', 'qo‘ymoq'],
  ['mean', 'anglatmoq'],
  ['keep', 'saqlamoq'],
  ['let', 'ruxsat bermoq'],
  ['begin', 'boshlamoq'],
  ['seem', 'tuyulmoq'],
  ['help', 'yordam bermoq'],
  ['talk', 'gaplashmoq'],
  ['turn', 'burilmoq'],
  ['start', 'boshlamoq'],
  ['might', 'ehtimol bo‘lmoq'],
  ['show', 'ko‘rsatmoq'],
  ['hear', 'eshitmoq'],
  ['play', 'o‘ynamoq'],
  ['run', 'yugurmoq'],
  ['move', 'harakatlanmoq'],
  ['like', 'yoqtirmoq'],
  ['live', 'yashamoq'],
  ['believe', 'ishonmoq'],
  ['hold', 'ushlamoq'],
  ['bring', 'olib kelmoq'],
  ['happen', 'sodir bo‘lmoq'],
  ['must', 'shart bo‘lmoq'],
  ['write', 'yozmoq'],
  ['provide', 'ta’minlamoq'],
  ['sit', 'o‘tirmoq'],
  ['stand', 'turmoq'],
  ['lose', 'yo‘qotmoq'],
  ['pay', 'to‘lamoq'],
  ['meet', 'uchrashmoq'],
  ['include', 'o‘z ichiga olmoq'],
  ['continue', 'davom ettirmoq'],
  ['set', 'o‘rnatmoq'],
  ['learn', 'o‘rganmoq'],
  ['change', 'o‘zgartirmoq'],
  ['lead', 'yetaklamoq'],
  ['understand', 'tushunmoq'],
  ['watch', 'tomosha qilmoq'],
  ['follow', 'ergashmoq'],
  ['stop', 'to‘xtamoq'],
  ['create', 'yaratmoq'],
  ['speak', 'gapirmoq'],
  ['read', 'o‘qimoq'],
  ['allow', 'ruxsat bermoq'],
  ['add', 'qo‘shmoq'],
  ['spend', 'sarflamoq'],
  ['grow', 'o‘smoq'],
  ['open', 'ochmoq'],
  ['walk', 'piyoda yurmoq'],
  ['win', 'g‘alaba qozonmoq'],
  ['offer', 'taklif qilmoq'],
  ['remember', 'eslamoq'],
  ['love', 'sevmoq'],
  ['consider', 'ko‘rib chiqmoq'],
  ['appear', 'paydo bo‘lmoq'],
  ['buy', 'sotib olmoq'],
  ['wait', 'kutmoq'],
  ['serve', 'xizmat qilmoq'],
  ['die', 'vafot etmoq'],
  ['send', 'yubormoq'],
  ['expect', 'kutmoq'],
  ['build', 'qurmoq'],
  ['stay', 'qolmoq'],
  ['fall', 'yiqilmoq'],
  ['cut', 'kesmoq'],
  ['reach', 'yetib bormoq'],
  ['kill', 'o‘ldirmoq'],
  ['remain', 'qolmoq'],
];

export const DEMO_COMMON_VERBS: Card[] = VERBS.map(([front, translation]) => ({
  front,
  translation,
  pos: "fe'l",
}));
